### ISSUE TITLE
Admin is blank

### ISSUE THREAD

**Issue by Tulleb** [cryptoapi/Bitcoin-Wordpress-Plugin#11]
Just after installing the plugin, my Wordpress admin dashboard is not displaying any content but the menu bar anymore. How can I fix it? Is it a compatibility issue?

I can only fix it by renaming the "gourl-bitcoin-payment-gateway-paid-downloads-membership" plugin folder...

I am using Wordpress 5.1.1–fr_FR.

**Comment by cryptoapi** [comment]
Please test on fresh wordpress installation / disable other WP plugins.
