### ISSUE TITLE
Freezing Wordpress

### ISSUE THREAD

**Issue by knoxcard2** [cryptoapi/Bitcoin-Wordpress-Plugin#15]
This plugin is completely crashing my Wordpress environment.  None of the pages would load.  Had to uninstall the plugin.

**Comment by cryptoapi** [comment]
No other reported this problem.

You can delete plugins folder -
 wp-content\plugins\gourl-bitcoin-payment-gateway-paid-downloads-membership\ 

You can test gourl bitcoin plugin on fresh wordpress installation without other plugins.
