### ISSUE TITLE
Confusing wording!

### ISSUE THREAD

**Issue by Sophivorus** [cryptoapi/Bitcoin-Wordpress-Plugin#2]
On the payment box it reads:

> "Send EXACTLY 0.123 BTC (plus minor fee) to:"

Why does it say "EXACTLY" and immediately after "plus minor fee"?? Do I need to send 0.123, or 0.123 + minor fee?? And it says that if I don't send the exact amount, the payment system will ignore it! This ambiguity is enough to make me cancel the payment, and I bet a lot of other users too.

The wording must be clarified!!!

**Comment by cryptoapi** [comment]
Updated to - 
"Send EXACTLY 0.00049542 BTC plus fees to"

**Comment by Sophivorus** [comment]
@cryptoapi Thanks for responding, but I think the new wording is still confusing! How about:

"Send EXACTLY 0.123 BTC (fees included) to"
