### ISSUE TITLE
Transaction fee

### ISSUE THREAD

**Issue by milossh** [cryptoapi/Bitcoin-Wordpress-Plugin#3]
What I don't understand here is that you say, on Github that there are no hidden fees, nor any fees whatsoever, and then make me create an account on your website, where, in your license agreement says that I accept some fees charged for the service by GoURL. What's the real deal here?

**Comment by cryptoapi** [comment]
It is standard Terms & Conditions.

Our fees - https://gourl.io/#section4
No hidden fees.
