### ISSUE TITLE
high fees

### ISSUE THREAD

**Issue by besoeasy** [cryptoapi/Bitcoin-Wordpress-Plugin#6]
hey can you make it to have and send using minimum fees possible

**Comment by cryptoapi** [comment]
Average bitcoin network transaction fees are $20-$150 per transaction, please use bitcoin cash/dash as alternative.

Our tweet - https://twitter.com/CryptocoinAPI/status/931673064340951042

**Comment by cryptoapi** [comment]
We try our best.

See live fees statistics - https://bitcoinfees.earn.com/

On bottom of page -
-----------------------
Which fee should I use?
The fastest and cheapest transaction fee is currently 420 satoshis/byte, shown in green at the top.
For the median transaction size of 226 bytes, this results in a fee of 94,920 satoshis.

**Comment by besoeasy** [comment]
but there should be an option on our site to have custom fees used
