### ISSUE TITLE
Wordpress Give Donation Addon

### ISSUE THREAD

**Issue by usaflees** [cryptoapi/Bitcoin-Wordpress-Plugin#8]
Hello AWESOME Devs of these great plugins.  Been using them for awhile and appreciate everything you have done for the community!  now thats out of the way.  Im having a problem with the Give donations wordpress plugin addon.  Ive added all of my payment boxes on the site with the keys etc.  The problem im having is when im clicking on donate it is trying to pull up a page called ?payment-mode=gourl and it isnt being found, am i forgetting something very simple?

**Comment by cryptoapi** [comment]
Please test on fresh wordpress installation / disable other WP plugins.
