### ISSUE TITLE
plugin won't work with require_secure_transport on

### ISSUE THREAD

**Issue by getorca** [cryptoapi/Bitcoin-Wordpress-Plugin#9]
plugin won't work with require_secure_transport on

After place order on the checkout page, the plugin returns an error "Server has returned error - Connections using insecure transport are prohibited while --require_secure_transport=ON"

**Comment by cryptoapi** [comment]
Here solution
https://www.digitalocean.com/community/questions/warning-mysqli_real_connect-hy000-3159-connections-using-insecure-transport-are-prohibited-while-require_secure_transport-on

**Comment by getorca** [comment]
That's not a solution, that's turning reqire_secure_transport off
